### PR TITLE
Remove the old commons-lang dependency

### PR DESCRIPTION
**Pull request by iherasymenko**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Removes a dependency to an extra library

* **What is the current behavior?** (You can also link to an open issue here)

The code uses an outdated commons-lang dependency

* **What is the new behavior (if this is a feature change)?**

To depend on commons-lang3 and commons-text only.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Comment by iherasymenko** [comment]
The `commons-text` dependency was added in 2da29cff9f729facdbc3520c73523da395b90dd4, but `StringEscapeUtils` was stiil imported from the old `commons-lang` library.

**Review by srbala — APPROVED** [review]
LGTM

**Comment by srbala** [comment]
Looks like good PR to accept

**Comment by iherasymenko** [comment]
@jan-moxter thanks for merging this. Could you please cut a new release with this change?

**Pull request merged**
